/**
 * Browser-side Midnight wiring for Candor — the REAL chain path.
 *
 * Wallet: Lace (dapp connector). Proofs: generated by Lace's built-in proving
 * API, so no local proof server is needed for the browser flow; the CLI flow
 * (packages/contract) uses a user-local proof server instead. In both cases
 * the witness (the salary) never leaves the contributor's machine.
 *
 * ZK artifacts (proving/verifier keys, zkIRs) are served from /zk/candor —
 * synced from packages/contract/src/managed/candor.
 */
import { setNetworkId, getNetworkId } from "@midnight-ntwrk/midnight-js-network-id";
import { FetchZkConfigProvider } from "@midnight-ntwrk/midnight-js-fetch-zk-config-provider";
import { dappConnectorProofProvider } from "@midnight-ntwrk/midnight-js-dapp-connector-proof-provider";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { levelPrivateStateProvider } from "@midnight-ntwrk/midnight-js-level-private-state-provider";
import {
  deployContract,
  findDeployedContract,
  type DeployedContract,
  type FoundContract,
} from "@midnight-ntwrk/midnight-js-contracts";
import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";
import { CostModel } from "@midnight-ntwrk/midnight-js-protocol/compact-runtime";
import { Contract as CandorContract } from "@candor/contract/managed/candor/contract";
import { witnesses, createPrivateState, type CandorPrivateState } from "@candor/contract/witnesses";
import { issuerCommitment } from "@candor/shared/hash";

export type CandorCircuitId = "submit" | "enroll" | "nextEpoch" | "getHistogram" | "readEpoch";

export const MIDNIGHT_NETWORKS = {
  preprod: {
    networkId: "preprod",
    indexer: "https://indexer.preprod.midnight.network/api/v5/graphql",
    indexerWS: "wss://indexer.preprod.midnight.network/api/v5/graphql/ws",
  },
} as const;

export type NetworkName = keyof typeof MIDNIGHT_NETWORKS;

export function isLaceAvailable(): boolean {
  return typeof window !== "undefined" && !!(window as any).midnight?.lace;
}

export type CandorProviders = {
  lace: any;
  // Circuit ids are branded strings in compact-js; the runtime fetch path is
  // id-agnostic, so the provider is intentionally typed loosely here.
  zkConfigProvider: FetchZkConfigProvider<any>;
  publicDataProvider: ReturnType<typeof indexerPublicDataProvider>;
  privateStateProvider: ReturnType<typeof levelPrivateStateProvider>;
  proofProvider: Awaited<ReturnType<typeof dappConnectorProofProvider>>;
  walletProvider: any;
  midnightProvider: any;
};

/** Connect to Lace and assemble the full provider bundle for Candor. */
export async function connectCandor(network: NetworkName = "preprod"): Promise<CandorProviders> {
  const cfg = MIDNIGHT_NETWORKS[network];
  setNetworkId(cfg.networkId);

  const lace = (window as any).midnight?.lace;
  if (!lace) throw new Error("Lace not found — install the Lace extension and reload");
  const api = await lace.connect(cfg.networkId);

  // Runtime fetches any circuit artifact; the narrow type param satisfies the
  // provider bundle's ProvableCircuitId constraint (impure circuits use the same fetch path).
  const zkConfigProvider = new FetchZkConfigProvider<CandorCircuitId>("/zk/candor");
  const publicDataProvider = indexerPublicDataProvider(cfg.indexer, cfg.indexerWS);
  const privateStateProvider = levelPrivateStateProvider({
    privateStateStoreName: "candor-private-state",
    signingKeyStoreName: "candor-signing-keys",
    privateStoragePasswordProvider: () => Promise.resolve(`candor-local-${getNetworkId()}`),
    accountId: "candor-web",
  });
  const proofProvider = await dappConnectorProofProvider(api, zkConfigProvider, CostModel.initialCostModel());

  return {
    lace: api,
    zkConfigProvider,
    publicDataProvider,
    privateStateProvider,
    proofProvider,
    walletProvider: api,
    midnightProvider: api,
  };
}

// The two-step pipe builder's R-bit inference (effect-ts) collapses through
// chained calls, so the assembled contract is typed as the runtime shape.
// Runtime behavior is fully typed at the callTx layer below.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compiledContract(): any {
  // keys/zkir are fetched from /zk/candor; witness code lives in @candor/contract
  const withWitnessesFn = CompiledContract.withWitnesses as any;
  const withAssetsFn = CompiledContract.withCompiledFileAssets as any;
  return withAssetsFn(withWitnessesFn(CompiledContract.make("candor", CandorContract), witnesses), "/zk/candor");
}

type CandorInstance = InstanceType<typeof CandorContract>;
type Found = FoundContract<CandorInstance>;
export type DeployedCandor = DeployedContract<CandorInstance>;

/**
 * Deploy Candor. The connected Lace wallet becomes the issuer: its private
 * state stores the issuerKey witness used by enroll/nextEpoch.
 */
export async function deployCandor(providers: CandorProviders, issuerKey: Uint8Array): Promise<DeployedCandor> {
  const ps: CandorPrivateState = { ...createPrivateState(), issuerKey };
  const deployed = (await deployContract(providers as any, {
    compiledContract: compiledContract(),
    privateStateId: "candor",
    initialPrivateState: ps,
    args: [issuerCommitment(issuerKey)],
  } as any)) as unknown as DeployedCandor;
  return deployed;
}

/** Connect to an already-deployed Candor instance. */
export async function findCandor(
  providers: CandorProviders,
  contractAddress: string,
  opts: { asIssuer?: boolean; issuerKey?: Uint8Array; secret?: Uint8Array } = {},
): Promise<Found> {
  // The user secret must be the SAME persistent value on every call: it derives
  // both the membership leaf and the epoch nullifier inside the circuit.
  const ps = opts.asIssuer
    ? { ...createPrivateState(opts.secret), issuerKey: opts.issuerKey }
    : createPrivateState(opts.secret);
  return (await findDeployedContract(providers as any, {
    compiledContract: compiledContract(),
    contractAddress,
    privateStateId: "candor",
    initialPrivateState: ps,
  } as any)) as unknown as Found;
}

/** Submit one bucketed salary — real on-chain transaction via Lace. */
export async function submitOnChain(
  providers: CandorProviders,
  contractAddress: string,
  opts: { cutKey: Uint8Array; bucket: number; secret: Uint8Array },
): Promise<any> {
  const found = await findCandor(providers, contractAddress, { secret: opts.secret });
  // callTx is typed per-circuit; the branded-key variance is looser at runtime
  return (found.callTx as any).submit(opts.cutKey, BigInt(opts.bucket));
}

/** Issuer-only: enroll a member leaf (operator wallet signs the tx). */
export async function enrollOnChain(
  providers: CandorProviders,
  contractAddress: string,
  opts: { memberLeaf: Uint8Array; issuerKey: Uint8Array },
): Promise<any> {
  const found = await findCandor(providers, contractAddress, { asIssuer: true, issuerKey: opts.issuerKey });
  return (found.callTx as any).enroll(opts.memberLeaf);
}

/** Issuer-only: advance the epoch, re-opening submissions for everyone. */
export async function nextEpochOnChain(
  providers: CandorProviders,
  contractAddress: string,
  opts: { issuerKey: Uint8Array },
): Promise<any> {
  const found = await findCandor(providers, contractAddress, { asIssuer: true, issuerKey: opts.issuerKey });
  return (found.callTx as any).nextEpoch();
}

// ---- session helpers -------------------------------------------------------

const ADDR_KEY = "candor:contractAddress";

export function getStoredContractAddress(): string | null {
  try {
    return localStorage.getItem(ADDR_KEY);
  } catch {
    return null;
  }
}

export function setStoredContractAddress(address: string): void {
  localStorage.setItem(ADDR_KEY, address);
}
